### PR TITLE
parse body if empty and has media type detected

### LINKED ISSUE #99: getParsedBody() not working in slim v4
In https://github.com/slimphp/Slim-Http/blob/master/src/ServerRequest.php#L165

```php
        $parsedBody = $this->serverRequest->getParsedBody();
        if ($parsedBody !== null) {
            return $parsedBody;
        }
```

The `$parsedBody` is checked against null. When a POST request is received with `Content-Type: application/json` the php server will set `$_POST` to an empty array.

In 
https://github.com/Nyholm/psr7-server/blob/master/src/ServerRequestCreator.php#L54
https://github.com/Nyholm/psr7-server/blob/master/src/ServerRequestCreator.php#L75

The serverRequest $parsedBody is initialized to the empty array and fails the check above so no parsed body data is returned from `$request->getParsedBody();`.

### PR DESCRIPTION
**Pull request by esetnik**
Fixes #99

### CODE REVIEW

File: src/ServerRequest.php [hunk 1]
```diff
@@ -162,13 +162,13 @@ public function getParsedBody()
     {
         $parsedBody = $this->serverRequest->getParsedBody();
 
-        if ($parsedBody !== null) {
+        if (!empty($parsedBody)) {
             return $parsedBody;
```
Comment (shadowhand) [inline src/ServerRequest.php]: Honestly, I don't think this is the correct solution. nyholm/psr7 should be updated to not automatically set the parsed body, per PSR-7 spec:

```
     * If the request Content-Type is either application/x-www-form-urlencoded
     * or multipart/form-data, and the request method is POST, this method MUST
     * return the contents of $_POST.
     *
     * Otherwise, this method may return any results of deserializing
     * the request body content; as parsing returns structured content, the
     * potential types MUST be arrays or objects only. A null value indicates
     * the absence of body content.
```

Comment (esetnik) [reply src/ServerRequest.php]: As I understand it, nyholm/psr7 is correct implementation. In the case of a json $_POST they  should not send null they should send empty array. See the discussion in #99.

Comment (l0gicgate) [reply src/ServerRequest.php]: We could do a null check based on content type then. If it is `application/x-www-form-urlencoded` or `multipart/form-data` we do a null check otherwise parse the body.

Comment (shadowhand) [reply src/ServerRequest.php]: @l0gicgate Slim doesn't need to solve this problem, IMO. It is a bug in nyholm/psr7, which is clearly not following the spec by blindly setting `withParsedBody($post)` without checking the request `Content-Type`.

Comment (l0gicgate) [reply src/ServerRequest.php]: It’s also a problem with Zend-Diactoros.

Comment (shadowhand) [reply src/ServerRequest.php]: Alright, if the problem exists beyond one implementation then I agree this is a reasonable solution.

Comment (esetnik) [reply src/ServerRequest.php]: It seems that the spec wasn't really considering the possibility that multiple layers would attempt to parse the body. There's no way to pass information on whether body parsing was attempted already.

**Comment by akrabat** [comment]
As an aside, it's nice that Slim-Psr7's `ServerRequestFactory` gets [this right](https://github.com/akrabat/Slim-Psr7/blob/master/src/Factory/ServerRequestFactory.php#L105-L108)!
